# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(689, 475)
        self.browser_action = QAction(MainWindow)
        self.browser_action.setObjectName(u"browser_action")
        self.lock_action = QAction(MainWindow)
        self.lock_action.setObjectName(u"lock_action")
        self.quit_action = QAction(MainWindow)
        self.quit_action.setObjectName(u"quit_action")
        self.dashboard_interface = QAction(MainWindow)
        self.dashboard_interface.setObjectName(u"dashboard_interface")
        self.control_interface = QAction(MainWindow)
        self.control_interface.setObjectName(u"control_interface")
        self.console_interface = QAction(MainWindow)
        self.console_interface.setObjectName(u"console_interface")
        self.env_interface = QAction(MainWindow)
        self.env_interface.setObjectName(u"env_interface")
        self.env_group_interface = QAction(MainWindow)
        self.env_group_interface.setObjectName(u"env_group_interface")
        self.dev_token_interface = QAction(MainWindow)
        self.dev_token_interface.setObjectName(u"dev_token_interface")
        self.sandbox_interface = QAction(MainWindow)
        self.sandbox_interface.setObjectName(u"sandbox_interface")
        self.twofa_settings = QAction(MainWindow)
        self.twofa_settings.setObjectName(u"twofa_settings")
        self.userdata_settings = QAction(MainWindow)
        self.userdata_settings.setObjectName(u"userdata_settings")
        self.keypair_settings = QAction(MainWindow)
        self.keypair_settings.setObjectName(u"keypair_settings")
        self.confirm_administration = QAction(MainWindow)
        self.confirm_administration.setObjectName(u"confirm_administration")
        self.invite_administration = QAction(MainWindow)
        self.invite_administration.setObjectName(u"invite_administration")
        self.api_logs = QAction(MainWindow)
        self.api_logs.setObjectName(u"api_logs")
        self.site_logs = QAction(MainWindow)
        self.site_logs.setObjectName(u"site_logs")
        self.worker_logs = QAction(MainWindow)
        self.worker_logs.setObjectName(u"worker_logs")
        self.my_queue_administration = QAction(MainWindow)
        self.my_queue_administration.setObjectName(u"my_queue_administration")
        self.api_logs_2 = QAction(MainWindow)
        self.api_logs_2.setObjectName(u"api_logs_2")
        self.site_logs_2 = QAction(MainWindow)
        self.site_logs_2.setObjectName(u"site_logs_2")
        self.worker_logs_2 = QAction(MainWindow)
        self.worker_logs_2.setObjectName(u"worker_logs_2")
        self.action_history = QAction(MainWindow)
        self.action_history.setObjectName(u"action_history")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 689, 33))
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setObjectName(u"file_menu")
        self.interface_menu = QMenu(self.menubar)
        self.interface_menu.setObjectName(u"interface_menu")
        self.logs_menu = QMenu(self.interface_menu)
        self.logs_menu.setObjectName(u"logs_menu")
        self.settings_menu = QMenu(self.menubar)
        self.settings_menu.setObjectName(u"settings_menu")
        self.administration_menu = QMenu(self.menubar)
        self.administration_menu.setObjectName(u"administration_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.statusbar.setFont(font)
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.settings_menu.menuAction())
        self.menubar.addAction(self.interface_menu.menuAction())
        self.menubar.addAction(self.administration_menu.menuAction())
        self.file_menu.addAction(self.browser_action)
        self.file_menu.addAction(self.lock_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.quit_action)
        self.interface_menu.addAction(self.dashboard_interface)
        self.interface_menu.addAction(self.control_interface)
        self.interface_menu.addAction(self.console_interface)
        self.interface_menu.addAction(self.logs_menu.menuAction())
        self.interface_menu.addSeparator()
        self.interface_menu.addAction(self.env_interface)
        self.interface_menu.addAction(self.env_group_interface)
        self.interface_menu.addAction(self.dev_token_interface)
        self.interface_menu.addSeparator()
        self.interface_menu.addAction(self.sandbox_interface)
        self.logs_menu.addAction(self.api_logs_2)
        self.logs_menu.addAction(self.site_logs_2)
        self.logs_menu.addAction(self.worker_logs_2)
        self.settings_menu.addAction(self.userdata_settings)
        self.settings_menu.addAction(self.twofa_settings)
        self.settings_menu.addAction(self.keypair_settings)
        self.administration_menu.addAction(self.confirm_administration)
        self.administration_menu.addAction(self.action_history)
        self.administration_menu.addAction(self.invite_administration)
        self.administration_menu.addSeparator()
        self.administration_menu.addAction(self.my_queue_administration)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.browser_action.setText(QCoreApplication.translate("MainWindow", u"Browser", None))
        self.lock_action.setText(QCoreApplication.translate("MainWindow", u"Sperren", None))
        self.quit_action.setText(QCoreApplication.translate("MainWindow", u"Beenden", None))
        self.dashboard_interface.setText(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.control_interface.setText(QCoreApplication.translate("MainWindow", u"Steuerung", None))
        self.console_interface.setText(QCoreApplication.translate("MainWindow", u"Konsole", None))
        self.env_interface.setText(QCoreApplication.translate("MainWindow", u"Umgebungsvariablen", None))
        self.env_group_interface.setText(QCoreApplication.translate("MainWindow", u"Umgebungsgruppen", None))
        self.dev_token_interface.setText(QCoreApplication.translate("MainWindow", u"Entwicklertokens", None))
        self.sandbox_interface.setText(QCoreApplication.translate("MainWindow", u"Meine Sandbox", None))
        self.twofa_settings.setText(QCoreApplication.translate("MainWindow", u"2FA einrichten", None))
        self.userdata_settings.setText(QCoreApplication.translate("MainWindow", u"Benutzerdaten", None))
        self.keypair_settings.setText(QCoreApplication.translate("MainWindow", u"Schl\u00fcsselpaar rotieren", None))
        self.confirm_administration.setText(QCoreApplication.translate("MainWindow", u"Aktionen best\u00e4tigen", None))
        self.invite_administration.setText(QCoreApplication.translate("MainWindow", u"Nutzer einladen", None))
        self.api_logs.setText(QCoreApplication.translate("MainWindow", u"Admin API", None))
        self.site_logs.setText(QCoreApplication.translate("MainWindow", u"Hauptseite", None))
        self.worker_logs.setText(QCoreApplication.translate("MainWindow", u"Worker", None))
        self.my_queue_administration.setText(QCoreApplication.translate("MainWindow", u"Meine Aktionen", None))
        self.api_logs_2.setText(QCoreApplication.translate("MainWindow", u"API", None))
        self.site_logs_2.setText(QCoreApplication.translate("MainWindow", u"Site", None))
        self.worker_logs_2.setText(QCoreApplication.translate("MainWindow", u"Worker", None))
        self.action_history.setText(QCoreApplication.translate("MainWindow", u"Aktionsverlauf", None))
        self.file_menu.setTitle(QCoreApplication.translate("MainWindow", u"Datei", None))
        self.interface_menu.setTitle(QCoreApplication.translate("MainWindow", u"Interface", None))
        self.logs_menu.setTitle(QCoreApplication.translate("MainWindow", u"Server Logs", None))
        self.settings_menu.setTitle(QCoreApplication.translate("MainWindow", u"Einstellungen", None))
        self.administration_menu.setTitle(QCoreApplication.translate("MainWindow", u"Administration", None))
#if QT_CONFIG(statustip)
        self.statusbar.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(accessibility)
        self.statusbar.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.statusbar.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
    # retranslateUi

